### PR TITLE
fix: issue #6

### LINKED ISSUE #6: Travis CI Test Failure
Travis CI fails with following error:

# github.com/smacker/opentracing-go-redis
./otredis.go:24:11: ctxClient.WrapProcess undefined (type *redis.Client has no field or method WrapProcess)
./otredis.go:25:11: ctxClient.WrapProcessPipeline undefined (type *redis.Client has no field or method WrapProcessPipeline)

### PR DESCRIPTION
**Pull request by thebinary**
add dep lock and use in travis ci.

### CODE REVIEW

**Comment by smacker** [comment]
Is there any particular reason to use `dep` instead of `go modules`?

P.S. Thanks a lot for taking care of the bug. I'm too busy at the moment to work on it.

**Comment by thebinary** [comment]
There is no such particular reason for selecting go dep. But, golang [Modules](https://github.com/golang/go/wiki/Modules) article mentions the support to be experimental as of 1.11 and plan for incorporating only in 1.13.

**Comment by nvx** [comment]
Go 1.12 already has go module support enabled by default in "auto" mode. This means if running go commands inside the GOPATH module support is off, or if running outside the GOPATH module support is on.

The Go 1.13 change is that module support will be always on by default, even inside GOPATH.

**Comment by smacker** [comment]
Thank you for your contribution. Though I would prefer to use go modules as it's a new standard for module versioning in go. The issue was fixed in #8

**Pull request closed without merging**
